### ISSUE TITLE
app doesn't ask for local network access; errors out at "DSU server running error"

### ISSUE THREAD

**Issue by kid335** [breeze2/dsu-controller-guides#1]
Just installed the app, and just this happens. In settings there isn't a toggle for local network access (idk how to label im sorry)

**Comment by breeze2** [comment]
Android or iOS? When the server runs with an error, the app will show it and close server. It doesn't matter, you can restart server on the app settings page.
In addition, the app needs local network permission, please configure it in the system settings.

**Comment by breeze2** [comment]
![IMG_0807](https://user-images.githubusercontent.com/5266711/225911357-797cae15-7dbe-48c3-875a-815c85ee3b73.PNG)
Does the app appear on the list of Local Network? Try to turn it on.
By the way, the port number (26760) may be taken. Close server, set the port number to 0 and restart server, the app will find a available port number.

**Comment by kid335** [comment]
I had wiimote_dsu open, using up the dsu server port. User error
