### ISSUE TITLE
Where the DSU Controller address

### ISSUE THREAD

**Issue by Lisandroa2010** [breeze2/dsu-controller-guides#11]
I wanna conect DSU Controller with DSU Manager but qrcode not work i try manual but i no Know where my DSU address is

**Comment by breeze2** [comment]
`DSU address = ip + ':' + port`
As the image shows，the DSU address is `192.168.101.2:26760`.
The QR Code issue will be fixed in the next version.


<img src="https://github.com/breeze2/dsu-controller-guides/assets/5266711/b0478600-95c6-4710-a9d5-59cfced2c971" alt="Configure Controls" width="360"/>

**Comment by Lisandroa2010** [comment]
that works thank you
