### ISSUE TITLE
Wiimote on Cemu doesn't work

### ISSUE THREAD

**Issue by mx4address** [breeze2/dsu-controller-guides#13]
I tried to use the Wiimote controller on Cemu but it doesn't work.. It'll register button presses but pointer movement doesn't work

**Comment by mx4address** [comment]
anyone?

**Comment by breeze2** [comment]
If you are running on Windows OS, connect DSUController to [DSUManager](https://github.com/breeze2/dsu-controller-guides?tab=readme-ov-file#run-with-dsu-manager-on-windows), you will get a virtual xbox360 controller, and then you can use it with Cemu as a Wiimote

**Comment by breeze2** [comment]
Hope [it](https://github.com/breeze2/dsu-controller-guides/?tab=readme-ov-file#run-with-cemu-20) helps: https://github.com/breeze2/dsu-controller-guides/?tab=readme-ov-file#run-with-cemu-20
