### ISSUE TITLE
Unresponsive Control

### ISSUE THREAD

**Issue by DakariMona** [breeze2/dsu-controller-guides#19]
The controller was sometimes unresponsive when I'm trying to throw PokeBall at pokemon I waste a ball because I can't aim it's unresponsive I have to unleash the button before I can aim so I will waste one PokeBall if this is not fixed I will use other app

**Comment by breeze2** [comment]
What does 'sometimes unresponsive' mean? The communication is based on Wi-Fi. How does it perform when the Wi-Fi signal is full?

**Comment by mono421** [comment]
So it's like this I have haptic feedback or smt on and when it's not respond it will not vibrating

**Comment by breeze2** [comment]
Do you mean the app is stuck? Will the joystick follow you when you drag it?

**Comment by mono421** [comment]
> Do you mean the app is stuck? Will the joystick follow you when you drag it?

The joystick not follow me

**Comment by mono421** [comment]
> Do you mean the app is stuck? Will the joystick follow you when you drag it?

https://github.com/breeze2/dsu-controller-guides/assets/80322542/d50384bc-e014-423e-8654-b52f6d956da4

**Comment by breeze2** [comment]
OK, I see.
I'll try to reproduce and fix.

**Comment by mono421** [comment]
> OK, I see.
> I'll try to reproduce and fix.

Thanks.

**Comment by breeze2** [comment]
It is on testing, you can try it from https://play.google.com/apps/testing/com.dsucontroller .

**Comment by mono421** [comment]
> It is on testing, you can try it from https://play.google.com/apps/testing/com.dsucontroller .

Ok I'll test it I'll tell you if it's still there
