### ISSUE TITLE
[Feature request] Touch control and Rumble 

### ISSUE THREAD

**Issue by DakariMona** [breeze2/dsu-controller-guides#20]
I want touch control and Rumble if it possible on yuzu this is all I want. There is nothing I want more

**Comment by breeze2** [comment]
![image](https://github.com/breeze2/dsu-controller-guides/assets/5266711/7b19db57-eed7-46d9-85a0-e71b50d75882)
Check the `Vibration`, you will get rumble.
And what does the `touch control` mean?

**Comment by mono421** [comment]
> ![image](https://github.com/breeze2/dsu-controller-guides/assets/5266711/7b19db57-eed7-46d9-85a0-e71b50d75882)
> Check the `Vibration`, you will get rumble.
> And what does the `touch control` mean?

I'll try the rumble

**Comment by mono421** [comment]
Okay it's work sorry and what about touch

**Comment by breeze2** [comment]
For now, using a mouse to simulate screen touches is simple and effective, but mapping screen touches from the app is relatively hard.
