### ISSUE TITLE
pointer not working

### ISSUE THREAD

**Issue by bargmy** [breeze2/dsu-controller-guides#31]
i have galaxy note5 it has accelerometer and gyroscope but pointer wont work somehow? i used default settings that is included on website..  any solution? 
![image](https://github.com/user-attachments/assets/0d6468ff-830f-457b-be56-c8724842465a)
i didnt change anything :L other buttons work

**Comment by bargmy** [comment]
its working now cant elete the iissue sorry

**Comment by breeze2** [comment]
It's okay, just close it.
