### ISSUE TITLE
能不能生产迷你的手机外设？

### ISSUE THREAD

**Issue by dutry** [breeze2/dsu-controller-guides#33]
很多手柄做不好都是陀螺仪等等用料不够，而 dsu 的问题在于手感太差不能盲按，如果能出迷你的 typec 的外设就好了，成本也低，只需要映射内部 api 的按键就行了

**Comment by dutry** [comment]
最好就是很小、很便携，像钥匙串那样，因为大部分人都不会随身带手柄，但大多有手机和电脑

**Comment by breeze2** [comment]
这个功能在应用中已经实现了，设置页面里可以使用手机连接的手柄。
你可以在市场上购买合适的手机手柄来使用。
我生产不了硬件😂

**Comment by dutry** [comment]
噢噢！好的啊！
