### ISSUE TITLE
这是mac上唯一可用的dsu客户端, 希望添加多手柄支持

### ISSUE THREAD

**Issue by dutry** [breeze2/dsu-controller-guides#34]
mac app store 可以下载和使用。dolphin 模拟器的 subreddit 一直有人问 betterjoy 的 mac 替代，但目前都没有

因此希望能添加 4 个 local gamepad，从而正式成为 mac 上 betterjoy 的高级替代

**Comment by breeze2** [comment]
功能上已经实现了，如果有多台手机，就可以实现多个虚拟手柄。
在输入源里输入所有手机的 DSUServer 地址 `ip:port`，然后像 Wii Remote 1 那样配置 Wii Remote 2、Wii Remote 3 和 Wii Remote 4。
![image](https://github.com/user-attachments/assets/9084592c-0bc6-4813-aa0d-782239fb3a0d)

**Comment by dutry** [comment]
@breeze2 如果能单手机多手柄就好了

还有一个问题，就是好像不支持手柄的体感是吗？

**Comment by breeze2** [comment]
是的，本意就是一个手机模拟一个体感手柄，普通手柄不需要通过手机再连接电脑
