### ISSUE TITLE
[Dolphin] Is it possible to shake the controller?

### ISSUE THREAD

**Issue by frog8412** [breeze2/dsu-controller-guides#39]
The shake isn't mapped to anything by default, and I dont know what to map to shaking, currently I can't spin/use the Propeller Suit in NSMBWii.

**Comment by breeze2** [comment]
Please make sure your phone has an accelerometer and gyroscope，and follow the [guides](https://github.com/breeze2/dsu-controller-guides?tab=readme-ov-file#run-with-dolphin) to configure the Controller Settings of Dolphin.

You can see that shaking works:
https://youtu.be/zavndVuGsIM?si=qX5c3iH4qlF57Vko

**Comment by frog8412** [comment]
> Please make sure your phone has an accelerometer and gyroscope，and follow the [guides](https://github.com/breeze2/dsu-controller-guides?tab=readme-ov-file#run-with-dolphin) to configure the Controller Settings of Dolphin.

The DSUController.ini sets shaking to Middle Click, and yes, I have accelerometer and gyroscope.
![image](https://github.com/user-attachments/assets/901d83d3-a70f-44e6-b06a-1b3b25e4ea7d)

**Comment by breeze2** [comment]
Ignore **Motion Simulation**, just look at **Motion Input**

<img width="1100" alt="motion input" src="https://github.com/breeze2/dsu-controller-guides/assets/5266711/c5615361-17a9-4907-abc8-634b757bae14">

**Comment by breeze2** [comment]
For NSMBWii, attach MotionPlus, And don't use any extensions.

![image](https://github.com/user-attachments/assets/13bad864-ea92-4bbe-9200-d6da133bf0fc)

**Comment by frog8412** [comment]
![изображение](https://github.com/user-attachments/assets/f36b0522-717f-46eb-9ac3-bd58b2636292)
![изображение](https://github.com/user-attachments/assets/4c757095-593e-4a25-982b-b99cf6e93e21)

**Comment by breeze2** [comment]
Do the red and blue dots move when you shake your phone?

**Comment by frog8412** [comment]
> Do the red and blue dots move when you shake your phone?

what dots
![Screenshot_2024-09-04-18-46-47-005_com dsucontroller](https://github.com/user-attachments/assets/eb476898-0b30-4b9c-b9b1-f70e29a477d8)
(took screenshot while shaking)

**Comment by frog8412** [comment]
Yes, they do

**Comment by frog8412** [comment]
Had to use a VM for the latest Dolphin (glad the performance is still good enough)

**Comment by DarkLord4563** [comment]
I have the same issue
