### ISSUE TITLE
After the 2.0 update on iOS the motion controls are broken

### ISSUE THREAD

**Issue by JupiMay** [breeze2/dsu-controller-guides#5]

**Comment by breeze2** [comment]
If you are talking about the Nunchuk controller, you can update the [DSUController_with_Nunchuk.ini](https://github.com/breeze2/dsu-controller-guides/blob/main/configs/dolphin/DSUController_with_Nunchuk.ini) follow the [documentation](https://github.com/breeze2/dsu-controller-guides#faq).

**Comment by JupiMay** [comment]
I'm talking about the pointer and all the motion controls, when pointing it just goes by himself and for example using mario kart is impossible. Tried on an android phone and it's perfect. On iOS I'm having that problem since the update got released

**Comment by breeze2** [comment]
As the video shows, the kart follows my phone motion.
Can you show me your controller configuration, like a screenshot or `*.ini` file.

https://github.com/breeze2/dsu-controller-guides/assets/5266711/098faf79-df9a-4ac2-8b44-9ec650ad8151

**Comment by JupiMay** [comment]
The controls work but are buggy, I'll send you the config

**Comment by JupiMay** [comment]
[Profile]
Device = DSUClient/0/
Buttons/A = Cross
Buttons/B = Square
Buttons/1 = Triangle
Buttons/2 = Circle
Buttons/- = Share
Buttons/+ = Options
Buttons/Home = PS
IR/Up = `Cursor Y-`
IR/Down = `Cursor Y+`
IR/Left = `Cursor X-`
IR/Right = `Cursor X+`
Tilt/Modifier/Range = 50.0
Shake/X = `Middle Click`
Shake/Y = `Middle Click`
Shake/Z = `Middle Click`
IMUAccelerometer/Up = `Accel Up`
IMUAccelerometer/Down = `Accel Down`
IMUAccelerometer/Left = `Accel Left`
IMUAccelerometer/Right = `Accel Right`
IMUAccelerometer/Forward = `Accel Forward`
IMUAccelerometer/Backward = `Accel Backward`
IMUGyroscope/Pitch Up = `Gyro Pitch Up`
IMUGyroscope/Pitch Down = `Gyro Pitch Down`
IMUGyroscope/Roll Left = `Gyro Roll Left`
IMUGyroscope/Roll Right = `Gyro Roll Right`
IMUGyroscope/Yaw Left = `Gyro Yaw Left`
IMUGyroscope/Yaw Right = `Gyro Yaw Right`
Classic/Left Stick/Modifier/Range = 50.0
Classic/Right Stick/Modifier/Range = 50.0
Guitar/Stick/Modifier/Range = 50.0
Drums/Stick/Modifier/Range = 50.0
Turntable/Stick/Modifier/Range = 50.0
uDraw/Stylus/Modifier/Range = 50.0
Drawsome/Stylus/Modifier/Range = 50.0
Rumble/Motor = `Motor 0`
D-Pad/Up = `Pad N`
D-Pad/Down = `Pad S`
D-Pad/Left = `Pad W`
D-Pad/Right = `Pad E`
That's the ini file

**Comment by breeze2** [comment]
I use Dolphin 5.0-19368, your ini and DSUController 2.0, the motion data is fine.
Upside down your phone, you should see the accelerometer is inverted, and all motion data is almost static.
<img width="1100" alt="motion input" src="https://github.com/breeze2/dsu-controller-guides/assets/5266711/c5615361-17a9-4907-abc8-634b757bae14">

**Comment by JupiMay** [comment]
After a while it began to work normally, hopefully it'll continue like that. Thanks for answering me!
