### ISSUE TITLE
(Android)The A button doesnt fit on the screen and rumble

### ISSUE THREAD

**Issue by Benmiki** [breeze2/dsu-controller-guides#8]
Some buttons are too big and don't fit the screen.
![Screenshot_20230621-144833_DSUController](https://github.com/breeze2/dsu-controller-guides/assets/136172698/0f8eb6fc-34c2-48a9-9a22-eb4625ad35ee)

Another problem is that the phone vibrates/rumbles whenever I press a button. Is it intentional or is it a bug?

**Comment by breeze2** [comment]
Ok, I will adjust the size of the button in the next version.
When a button is pressed, the phone vibrates for [haptic feedback](https://en.wikipedia.org/wiki/Haptic_technology).
It makes you feel like pressing a real button (maybe not very well 😂). Maybe I should add a switch to control whether haptic feedback is on or not.

**Comment by breeze2** [comment]
It is fixed in the latest version.
