### ISSUE TITLE
Will native controller inputs work?

### ISSUE THREAD

**Issue by AmeliaGL0w0** [breeze2/dsu-controller-guides#9]
I mean by that if i connected my external controller (like a DS4) via this app, and then use my controller that way. I dont have much options since my computer doesn't have bluetooth and every single microusb cable in my home is either broken, doesnt lock in place and disconnects a ton, or 90% of them are just charging cabels.

**Comment by breeze2** [comment]
Now you can use native controllers with version 2.3.
